### PR TITLE
[WIP] Fix SpikeGeneratorGroup and other incompatibilities

### PR DESCRIPTION
**Pull request by mstimberg**
I only now realized that changes in Brian 2 that were published with the latest release unfortunately completely break the functionality of `SpikeGeneratorGroup` in Brian2GeNN. The reason is that we greatly improved the handling of periods in `SpikeGeneratorGroup`, which entailed a different default value for the period: before, we use a very large value (as a proxy for "infinite"), now we use 0. Brian2GeNN still used the old algorithm which unfortunately does not handle a period of 0 well at all. I fix this in this PR, and also slightly changed the way the time is advanced during a run which became necessary with the changes because `SpikeGeneratorGroup` now makes use of the integer timestep `iT`.

Unfortunately I also discovered one more thing, apparently I did not run the full test suite on the *GPU* with the latest changes in Brian2GeNN. @tnowotny : the change to use `iT` for `run_regularly` operations (#83) only seems to work for the CPU-only mode, not on the GPU. `iT` is a global host variable but cannot be accessed on the device. I do not see an easy fix in Brian2GeNN (I think in GeNN we could change the signature of the `calcNeurons` function to include `iT` in addition to `t`), but maybe you do? If not, a quick&easy solution would be of course to revert the change merged with #83, it was only meant as an optimization after all.

As soon as we have dealt with this, we should make a 1.3.1 release.

### CODE REVIEW

**Comment by tnowotny** [comment]
@neworderofjamie , we were making these changes to brian2genn where we are using iT instead of t to optimise a bit, but it is (kind of obviously) not working on GPU; what do you think about making iT available in kernels (as a passed variable) by default in addition to t? 
I have no strong opinion, we can also revert the changes in brian2genn...

**Comment by neworderofjamie** [comment]
I did start going down this road at some point (probably for similar performance reasons) but the problem is that ``iT`` is 64-bit which, as far as I can tell, no GPUs support natively, making almost anything you do with it very slow - https://devtalk.nvidia.com/default/topic/1038492/question-about-64-bit-integer-performance/ suggests multiplication is 20x slower than 32-bit and division (and thus probably %) are 80x slower. What exactly are you trying to do?

**Comment by tnowotny** [comment]
It is for deciding when to run the run_regularly code bits (stuff that runs only every N timesteps). As I remember it, it did not involve much computation. But of course, if we make it available by default, people may start using it?

**Comment by neworderofjamie** [comment]
My thinking is that fmod on the time is almost certainly faster AND means
'natural' units can be used throughout. As you say, if we expose it, people
will use it and it's likely to be unexpectedly slow

**Comment by tnowotny** [comment]
@mstimberg , I think the verdict is to revert my pull request #83 ... sorry for the noise ...

**Comment by mstimberg** [comment]
No worries, I agree that reverting is the best solution for now. We can always reconsider the implementation later.

**Pull request merged**
