### PR TITLE
This is a fix for issue #136. 

### PR DESCRIPTION
**Pull request by tnowotny**
The root cause for the problem was that for situations where sub-populations of neuron populations were connected
and a state monitor for the synapses instantiated, the pre-template prep code would identify the size of the connected sub-populations for the ```srcN``` and ```trgN``` variables of the ```stateMonitorModel```. These variables are then used for the argument list of the ```convert_dense_matrix_2_dynamic_arrays``` and ```convert_sparse_synapses_2_dynamic_arrays``` calls that translate GeNN synaptic data into brian format synaptic data. Because brian2genn implements sub-populations only by connectivity matrices between full populations, the conversion functions need the size of the full populations, not of the connected sub-populations.
I believe the ```srcN``` and ```trgN``` variables are solely for the purpose of these conversions, so should not be needed to represent sub-population size elsewhere.

### CODE REVIEW

**Comment by tnowotny** [comment]
Oh dear ... I see the tests are failing but I am afraid it is likely due to a change in Brian 2. The tests seem to pass locally with brian 2.4.2
And I have had problems with brian2genn and brian 2.5* ...

**Comment by kernfel** [comment]
Oops, based on the b2g release notes, I assumed compatibility with later brian2 versions was not guaranteed anyway, and didn't report my own failures on later/current brian2. Which is to say: Can confirm, brian2 > 2.4.2 breaks brian2genn.

**Comment by mstimberg** [comment]
Apologies, Brian2GeNN is indeed not compatible yet with Brian 2.5, but requirements and test suite do not reflect this. I'll try to take care of this tomorrow.

**Review by mstimberg — APPROVED** [review]
Looks good to me :+1:

**Comment by mstimberg** [comment]
I pushed changes to master to make Brian2GeNN compatible with Brian 2.5 and merged the changes into this branch. All tests pass, so this is good to merge.

**Comment by kernfel** [comment]
Excellent, thank you both!

**Pull request merged**
