### PR TITLE
Use Brian's general compiler preferences

### PR DESCRIPTION
**Pull request by mstimberg**
Not sure if you agree, but I think it might be simpler if Brian2GeNN just uses Brian's compiler optimization flags instead of GeNN-specific ones. Or do you think users will often set optimization flags differently for the two?

### CODE REVIEW

**Comment by tnowotny** [comment]
But what about if they want to set GPU (nvcc) compiler options?
(I am not sure whether this works in the previous version either though).
I guess we can go ahead with this and look at the nvcc compiler options independently.What do you think?

**Comment by mstimberg** [comment]
> But what about if they want to set GPU (nvcc) compiler options?

It's not ideal, I agree. The docs for the GeNN-specific preferences stated "the flags will be applied both for the nvcc compilation and C++ compiler compilation (e.g. gcc, clang)" but I think this was not actually true...

The nvcc compiler options are the same for Unix and Windows, right? How about having a separate (GeNN-specific) preference only for the nvcc options, and use the standard Brian ones for the C++ compilation?

**Comment by mstimberg** [comment]
Hmm, I just realized that we can't actually pass down nvcc compiler argument to the compiler call in the makefile of the `magicnetwork_model_CODE` folder (the only place where we call nvcc). This is something that would require changes in GeNN itself...

**Comment by tnowotny** [comment]
I think we can. We didn't do it previously (can't remember why - probably an oversight) but GeNN provides for the use of 
```
NVCC_OPTIMIZATIONFLAGS
```
which are then used in the `makefile_common_gnu.mk`
These optimization flags are indeed the same for unix and windows. So it could be just one genn specific preference and it would be included into the GNUmakefile and WINmakefile templates.
In GeNN we often use 
```
-use_fast_math -O3 
```

**Comment by mstimberg** [comment]
> I think we can. We didn't do it previously (can't remember why - probably an oversight) but GeNN provides for the use of
> 
> NVCC_OPTIMIZATIONFLAGS
> 
> which are then used in the makefile_common_gnu.mk

Yes, I saw that. These flags are not passed down to the makefile in the `SIM_CODE` folder, though. That makefile is generated by the `generate_runner.cc` and sets "hand-crafted" `NVCC_FLAGS` that will include `-use_fast_math -O3` if `GENN_PREFERENCES::optimizeCode` is set, but this is independent of the `NVCC_OPTIMIZATIONFLAGS`.

**Comment by tnowotny** [comment]
You are right ... these are two different pathways ...
hum ... not very elegant I must admit.

**Comment by tnowotny** [comment]
I think I would be happy to introduce GeNN preferences of the following flavour:
```
GENN_PREFERENCES::userCxxFlags
GENN_PREFERENCES::userNvccFlags
```
which would be used on top of the bespoke ones from `optimizeCode` if both were defined or on their own if the latter wasn't set.
Would that make things simple(r)?

**Comment by mstimberg** [comment]
Sounds good to me in principle (we'd still have to set the C++ flags in our make file as well so they are used when compiling the "pure Brian 2" stuff) -- which Brian2GeNN-generated file would set these preferences so that they are taken into account by `generate_runner`?

**Comment by tnowotny** [comment]
I believe it can go into the `model.cpp` template. I will introduce the new preferences to GeNN now.

**Comment by mstimberg** [comment]
> I believe it can go into the model.cpp template. I will introduce the new preferences to GeNN now.

Ok great, let me know when it is done, I can then add stuff on the Brian2GeNN side.

**Comment by tnowotny** [comment]
Ok - this now done. It's introduced to both the GeNN master branch and the GeNN development branch.
the preferences are named
```
GENN_PREFERENCES::userCxxFlagsWIN
GENN_PREFERENCES::userCxxFlagsGNU
GENN_PREFERENCES::userNvccFlags
```
with the obvious meaning.
They are best set within the `modelDefinition()` function within the model.cpp template.
I agree with your earlier suggestion that the `userCxxFlagsWIN` and `userCxxFlagsGNU` could originate from the corresponding Brian 2 preferences and teh `userNvccFlags` could be a brian2genn preference.

**Comment by mstimberg** [comment]
Ok, I added support for a new nvcc preference to Brian2GeNN -- it seems to work but it could certainly benefit from some testing (e.g. I did not try it on Windows). Let me know what you think.
I also added the nvcc compiler flags as `NVCC_OPTIMIZATIONFLAGS` to the make file, even though they are not currently used anywhere. Who knows, it might be useful in the future.

**Comment by tnowotny** [comment]
I had a quick look over all changes and it looks v. good.
I think I will merge the pull request now. Unfortunately I also don't have a functional Windows setup. So it's a bit ad hoc. Maybe I can convince James to do some testing on his Windows box.

**Comment by mstimberg** [comment]
> Unfortunately I also don't have a functional Windows setup. So it's a bit ad hoc.

Related to that, I think I will try to set up automatic testing for Linux/OS-X/Windows (as we have for Brian itself) -- it will be very basic as we can of course only test the CPU-only mode, but at least it should make sure that the Brian2-Brian2GeNN-GeNN pipeline works at least in principle.

**Comment by tnowotny** [comment]
That would be extremely helpful. The GPU specifics are mostly a GeNN issue, so if CPU_only works, it is a good indication that everything should work ... with caveats like the NVCC flags we just introduced ...

**Comment by jamesturner246** [comment]
I'm not sure if this changes anything, but the flags used in the code-generation phase need to be the same as those generated and put into the model_CODE/Makefile, since using different optimisation flags changes the amount of registers and shared memory used by a kernel.

As long as the nvcc flags for model_CODE/* match up at code-generation and compile time, it's OK.

**Comment by tnowotny** [comment]
I think we are doing that.

**Comment by mstimberg** [comment]
We do not seem to take the optimisation flags into account for the "dry-run compile" phase, though. Is that a problem?

**Comment by tnowotny** [comment]
Ah, yes ... my mistake. I didn't catch all the places where the extra flags are necessary. This has now been amended in genn. Hopefully I got them all this time round. No action from the side of brian2genn should be necessary.

**Pull request merged**
