### PR TITLE
Update to support Python 3

### PR DESCRIPTION
**Pull request by neworderofjamie**
I used six to solve the various iterable issues in a way that should be efficient for Python 2.7 and 3

### CODE REVIEW

**Comment by tnowotny** [comment]
tests are not looking good but I will try some manual testing tomorrow ...

**Comment by mstimberg** [comment]
As you might have noticed, I have added a few commits to make the test suite working. Some issues actually required fixes in Brian 2 and releasing new maintenance releases :roll_eyes: 

The main changes:
* I removed the Python 2.7 tests against Brian 2 master, since Brian 2 master does not support Python 2 any more.
* There was a bug in Brian introduced with the switch to pytest, where the test suite was marked as failed because the "standalone-only" category did not find any brian2genn-specific tests in Brian's test suite. Nose signaled successful execution with error code 0 in that case, but pytest exits with a special error code 5.
* The manual setting of a compiler on Windows was not working correctly in the last Brian release (this was already fixed in Brian master), and we need this feature on the Azure Windows server to get the right Visual Studio version.
* The OS X 10.13 image we used for testing is no longer provided by Azure, we now use OS X 10.14 instead.
 * There were a few minor changes necessary in Brian2GeNN to make it compatible with latest Brian 2 master.

With all this, tests should now all pass, I hope. Note that for Python 2.7, it is important that we install Brian 2 with pip and not with conda, since conda-forge does not upload packages for Python 2 any more – the latest available conda package for Python 2.7 is therefore 2.3, whereas for Python 3 it is 2.3.0.2 (containing the fixes I mentioned earlier).

With that out of the way, I'll soon have a closer look at the actual content of this PR :smile: 

I'd suggest after its merge we'll do a release right away (without waiting for #101), since the situation is currently far from ideal. The latest Brian2GeNN release does not contain bugfixes necessary to correctly run with the latest Brian 2 release...

**Comment by tnowotny** [comment]
I agree, we should make a quick release now ASAP. Then it's on to #101 , which by the way is also shaping up nicely I think.

**Comment by mstimberg** [comment]
> I agree, we should make a quick release now ASAP. Then it's on to #101 , which by the way is also shaping up nicely I think.

Done! 
* https://pypi.org/project/Brian2GeNN/1.4/ 
* https://github.com/brian-team/brian2genn/releases/tag/1.4

**Comment by mstimberg** [comment]
Um, just realized that Brian2GeNN 1.4 would have been a good name for the release adding support for GeNN 4, but well :roll_eyes:

**Comment by tnowotny** [comment]
oh well ... never mind :-)

**Pull request merged**
