### PR TITLE
Automatic testing (CPU only) for Windows/Linux/OS-X

### PR DESCRIPTION
**Pull request by mstimberg**
It turned out that brian2genn was not quite working on Windows, I fixed a few issues and now it does (at least in CPU-only mode, I cannot test the GPU under Windows).

This PR enables automatic tests of the CPU-only mode on Windows (on appveyor) and Linux/OS-X (on travis), all tests seem to pass (with many `NotImplementedError`s of course).

Apart from the necessary configuration for the test servers, this branch also:
* clears up the file/directory structure a bit, separating the `brian2genn` package from scripts and other files
* removes the need for a `VS_PATH` environment variable on Windows -- we use distutils to search for `vcvarsall.bat`, otherwise the user can specify the path via a Brian preference.
* adds better error messages, i.e. it should now be clearer whether the compilation or the run failed and you'll get to see the actual error output.

Good to merge from my side!

### CODE REVIEW

**Comment by mstimberg** [comment]
Oh, just for completeness: Tests are done on Python 2.7 and Python 3.5. I did not bother with testing on a 32bit machine, so all are 64bit.

**Comment by tnowotny** [comment]
ok, looks good on face value - thanks a lot. I merged it in but we should keep an eye on the use of the GeNN development branch rather than master. Eventually we may want to go back to master (I am not up to date what was happening with GeNN development that you needed...).

**Comment by mstimberg** [comment]
> Eventually we may want to go back to master (I am not up to date what was happening with GeNN development that you needed...).

Sure, I am happy to go back to master as soon as we can. The reason why we need the development branch is @jamesturner246's recent commit related to `INCLUDE_FLAGS` on Windows (see genn-team/genn#110).

**Comment by tnowotny** [comment]
yes, thanks. I have seen the other thread now.

**Pull request merged**
