### PR TITLE
Support slow statemonitor clocks

### LINKED ISSUE #139: [Feature request] Support for slower clocks in Monitors
Since the output of any Monitor activity necessarily ends up in host memory and does not affect model evaluations, I feel it should be possible to provide slower clocks for these, with dt a multiple of the model clock. I don't have the time right now to dig into the code here, but would appreciate any pointers as to (a) whether this is a sensible and reasonably implementable request, and (b) if so, where to start to add such support.

Alternatively, smart workarounds to doing regular, but infrequent state monitoring during a long run would be an acceptable resolution, too. :)

Best, Felix

### PR DESCRIPTION
**Pull request by kernfel**
Fixes #139.

In order to maintain my sanity in the template code, I've also cleaned up indentation in templates/engine.cpp prior to implementing slow clock support.
I couldn't see any tests for slow clocks, but I've tested the feature to my satisfaction informally and confirmed locally that there are no regressions (at least as covered by unit tests).

### CODE REVIEW

**Comment by mstimberg** [comment]
Many thanks for contributing this feature! I will have a closer look at the code soon (but from a quick look I don't think there are any issues). I just pushed a new test for the "slow StateMonitor" feature to Brian's master branch and restarted the test suite in this PR, which means that the `..._latest` runs should pick up and execute the new test.

**Comment by mstimberg** [comment]
The new test run does not seem to be displayed in the GitHub UI, but you can find it here: https://dev.azure.com/brian-team/Brian2GeNN/_build/results?buildId=732&view=results

**Comment by tnowotny** [comment]
fwiw, it looks good to me!

**Comment by mstimberg** [comment]
All looks good to me, too, and the test suite successfully passed. Thanks again!

**Pull request merged**
