### PR TITLE
[MRG] Support single precision floats

### LINKED ISSUE #69: Support single precision
See discussion in brian-team/brian2#981 (currently needs Brian2 from master branch).

### PR DESCRIPTION
**Pull request by mstimberg**
Fixes #69 

This enables support for single precision floats in Brian2GeNN. For consistency with the way time is handled in Brian2, this uses GeNN's recently introduced `setTimePrecision` function to use double precision for the time variable `t`, regardless of the general precision setting. This is currently available in master, but not yet in a released version. In order not to have to wait for the GeNN 3.2 release, we only raise a warning if the GeNN version appears to be too old (which is a false positive for current GeNN master which still announces its version as 3.1.1).

### CODE REVIEW

**Comment by mstimberg** [comment]
Hmm, it doesn't look that great for non-Linux platforms currently -- should we merge nevertheless and figure this out later?
* OS X tests seem to hang and then time out
* Windows problem seems to be on the GeNN side. @tnowotny / @neworderofjamie: did you test the `setTimePrecision` feature also in CPU-only mode (this is what we are running on the test servers)?

**Comment by neworderofjamie** [comment]
``setTimePrecision`` definitely works in CPU-ONLY mode. I'll just grab my windows machine and check we haven't broken anything (our automated tests don't cover windows)

**Comment by neworderofjamie** [comment]
All combinations of CPU-ONLY mode and time precision seem to work fine on Windows - I don't think the issue is GeNN-side  I'm afraid

**Comment by tnowotny** [comment]
Hi Marcel,
I just started the benchmarks on my old MAC that has NVIDIA hardware and they seem to run fine (one exception is the use of the –I option for the date command in the bash script that doesn’t seem to work on OSX … but that is a mere detail).
I wonder what is going on the test server. I am running with the latest master branches of everything.
Best,
Thomas

--
Prof Thomas Nowotny
Director of Research and Knowledge Exchange
School of Engineering and Informatics
University of Sussex
Falmer, Brighton BN1 9QJ, UK
Phone: +441273678593
FAX: +441273877873

**Comment by tnowotny** [comment]
Spoken too soon: The cpp_standalone benchmarks fail because clang complains about 
```clang: error: unsupported option '-fopenmp'```
... but this might be a completely different problem?

**Comment by tnowotny** [comment]
argh ... just realized that this is because I had to downgrade XCode (and hence clang) inorder for it to get along with the CUDA install; the older clang has no openmp support. So just ignore me.

**Comment by mstimberg** [comment]
@neworderofjamie Thanks for looking into this! I'm afraid my remark about `setTimePrecision` was a red herring -- I realized that *all* of our CPU-only builds are failing with GeNN master on Windows, regardless of whether they use `setTimePrecision` or not...

I bisected the problem to this commit: genn-team/genn@9702f0bfb25 ("Final bit of Makefile work - can now generate Windows, CPU_ONLY makefiles for building GeNN models into shared libraries"). Maybe our [Windows makefile](https://github.com/brian-team/brian2genn/blob/master/brian2genn/templates/WINmakefile) has to change in some way?

If I understand the output correctly (also see: https://ci.appveyor.com/project/brianteam/brian2genn/build/1.0.306 ), I'm getting the error during the build of `runner.cc`:
```
cl /nologo /EHsc /C /DCPU_ONLY /Ox /w /arch:SSE2 /MP /I"C:\projects\brian2genn\genn\lib\include" runner.cc
runner.cc
LINK : fatal error LNK1561: entry point must be defined
```

**Comment by mstimberg** [comment]
Sorry, the commit link above was broken, here it is in a working form: genn-team/genn@9702f0b

**Comment by neworderofjamie** [comment]
Ahhh that does seem all too likely - the NMake build system is basically
deprecated in favour of MSbuild so I probably haven't tested that for ages

**Comment by neworderofjamie** [comment]
Could you try changing that capital /C to a lowercase /c in this line
``string cxxFlags = GENN_PREFERENCES::buildSharedLibrary ? "/LD" :
"/C";``

**Comment by mstimberg** [comment]
:astonished: that seems indeed to do the trick!

**Comment by neworderofjamie** [comment]
:scream: pushed a fix to master

**Comment by mstimberg** [comment]
Many thanks, I'll restart the tests and see whether this fixes it on the servers.

**Comment by mstimberg** [comment]
@neworderofjamie Thanks again for the quick fix, I can confirm that it works now on the test server. Do you think it would be a lot of work to switch our nmake-based build to msbuild? Brian2GeNN now depends on latest GeNN anyway, so we might as well go with the up-to-date way of using it.

@tnowotny & @thesamovar : I'm merging this now as it is, the OS X tests are still hanging for some reason, but this is probably quite specific to the travis setup, I think we can investigate this later.

I'm not deleting this branch for now to avoid issues with our benchmarking scripts, `master` and `support_float32` will therefore be identical for a while.

**Comment by neworderofjamie** [comment]
It SHOULD be trivial. The code generator will already be being built using msbuild which means everything **should** be working. All you should need to do is generate an vcxproj xml file like this rather than a WINmake:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="va_benchmark_CODE\generated_code.props" />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>%(AdditionalIncludeDirectories);$(BOB_ROBOTICS_PATH)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="simulator.cc" />
  </ItemGroup>
</Project>
```

(Replacing the path in the import directive with the name of your generated model and; adding any include directories and source files you require).
Then you just build it with ``msbuild /p:Configuration=Release project.vcxproj``. Available configurations are ``Release``, ``Debug``, ``Release_CPU_ONLY`` and ``Debug_CPU_ONLY.`` The main advantage is that, if you're that way inclined, you can double click on it and open it in visual studio for debugging, profiling etc.

**Pull request merged**
