### PR TITLE
Fix shared variables

### PR DESCRIPTION
**Pull request by tnowotny**
I think it is ready to be merged - locally all tests seem to pass. Of course, it would be great to add a new test that picks up on shared variables.
(would like to assign Felix to review but seems to be unable to)

### CODE REVIEW

**Comment by tnowotny** [comment]
I have implemented your suggestion, @mstimberg.  Would it make sense to add the simple test above as a brian test (as it seems shared variables are not tested - at least within the tests run for brian2genn)?

**Comment by mstimberg** [comment]
Great, thanks! I already added a test which tests shared variables with `run_regularly` to Brian2 `master`. All the `..._latest` test should pick it up. Let's wait for the tests to pass and then merge.

**Comment by tnowotny** [comment]
Extraordinarily, we still get these test failures on random branches:
```python
2020-07-08T13:11:15.4171370Z     @pytest.mark.standalone_compatible
2020-07-08T13:11:15.4172120Z     def test_synapse_generator_random():
2020-07-08T13:11:15.4172800Z         # The same tests as test_connection_random_without_condition, but using
2020-07-08T13:11:15.4173660Z         # the generator syntax
2020-07-08T13:11:15.4175450Z         G = NeuronGroup(4, '''v: 1
2020-07-08T13:11:15.4176730Z                               x : integer''', threshold='False')
2020-07-08T13:11:15.4177930Z         G.x = 'i'
2020-07-08T13:11:15.4179030Z         G2 = NeuronGroup(7, '''v: 1
2020-07-08T13:11:15.4180340Z                                y : 1''', threshold='False')
2020-07-08T13:11:15.4181460Z         G2.y = '1.0*i/N'
2020-07-08T13:11:15.4181980Z     
2020-07-08T13:11:15.4183020Z         S1 = Synapses(G, G2, 'w:1', 'v+=w')
2020-07-08T13:11:15.4184350Z         S1.connect(j='k for k in sample(N_post, p=0)')
2020-07-08T13:11:15.4184920Z     
2020-07-08T13:11:15.4186030Z         S2 = Synapses(G, G2, 'w:1', 'v+=w')
2020-07-08T13:11:15.4187720Z         S2.connect(j='k for k in sample(N_post, p=1)')
2020-07-08T13:11:15.4188350Z     
2020-07-08T13:11:15.4189240Z         # Just make sure using values between 0 and 1 work in principle
2020-07-08T13:11:15.4190440Z         S3 = Synapses(G, G2, 'w:1', 'v+=w')
2020-07-08T13:11:15.4191690Z         S3.connect(j='k for k in sample(N_post, p=0.3)')
2020-07-08T13:11:15.4192380Z     
2020-07-08T13:11:15.4194040Z         # Use pre-/post-synaptic variables for "stochastic" connections that are
2020-07-08T13:11:15.4194890Z         # actually deterministic
2020-07-08T13:11:15.4197180Z         S4 = Synapses(G, G2, 'w:1', on_pre='v+=w')
2020-07-08T13:11:15.4198900Z         S4.connect(j='k for k in sample(N_post, p=int(x_pre==2)*1.0)')
2020-07-08T13:11:15.4199720Z     
2020-07-08T13:11:15.4200500Z         with catch_logs() as _:  # Ignore warnings about empty synapses
2020-07-08T13:11:15.4201320Z             run(0*ms)  # for standalone
2020-07-08T13:11:15.4202660Z     
2020-07-08T13:11:15.4203280Z         assert len(S1) == 0
2020-07-08T13:11:15.4204150Z         _compare(S2, np.ones((len(G), len(G2))))
2020-07-08T13:11:15.4204870Z         assert 0 <= len(S2) <= len(G) * len(G2)
2020-07-08T13:11:15.4205750Z         assert len(S4) == 7
2020-07-08T13:11:15.4206410Z >       assert_equal(S4.i, np.ones(7)*2)
2020-07-08T13:11:15.4207290Z E       AssertionError: 
2020-07-08T13:11:15.4207910Z E       Arrays are not equal
2020-07-08T13:11:15.4208820Z E       
2020-07-08T13:11:15.4209390Z E       Mismatch: 100%
2020-07-08T13:11:15.4210100Z E       Max absolute difference: 2.0
2020-07-08T13:11:15.4210790Z E       Max relative difference: 1.0
2020-07-08T13:11:15.4211950Z E        x: array([0, 0, 1, 1, 1, 1, 1], dtype=int32)
2020-07-08T13:11:15.4212790Z E        y: array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.])
2020-07-08T13:11:15.4213370Z 
2020-07-08T13:11:15.4214890Z ../../test_env/lib/python2.7/site-packages/brian2/tests/test_synapses.py:2357: AssertionError
```
which seem very unlikely. They are clearly not related to the current PR, but I wonder whether there is something amiss with refreshing python arrays after the model run (are they not all invalidated correctly in the array cache?).
I suspect to merge this PR but have a look into this issue when there is some time ...

**Comment by mstimberg** [comment]
I agree that this is very odd (and unrelated to the current PR). Could you open an issue for it, this way we won't forget about it...

**Pull request merged**
