### PR TITLE
[MRG] Remove packaged GeNN

### LINKED ISSUE #53: Decide how to package Brian2GeNN
I think we are ready to publish a first official (beta?) release of Brian2GeNN, it now reasonably well detects unsupported features and it runs non-trivial examples like [Kremer et al. (2011)](http://brian2.readthedocs.io/en/stable/examples/frompapers.Kremer_et_al_2011_barrel_cortex.html).

I wonder what is the best way to package it, though. Brian2GeNN does of course depend on GeNN, but it would not make much sense to specify this dependence on the Python level, since GeNN is not a Python package (we won't upload it to pypi). In principle, we could create a conda package for GeNN, but given that it would not do much except for copying the files, I am not sure it is worth it.

One option I was considering: include the GeNN source code itself into Brian2GeNN via a submodule, and ship it alongside Brian2GeNN in pip/conda packages. I think this would be the most user-friendly option (a simple `pip install brian2genn` or `conda install -c brian-team brian2genn` would work), and it would also avoid potential conflicts with future versions of GeNN.

There is one problem with this solution, though: both pip and conda allow the installation of packages system-wide (even though it is uncommon for conda), so GeNN could end up in a location not writeable by users without administrator rights. During the compilation of GeNN projects, some files will be compiled to the source directory, so this would fail. Could we pre-compile these files when we create the conda package (let's not worry too much about pip, this could remain "semi-automatic", i.e. you'd still have to install GeNN independently), or do any of these files have to be re-compiled in a project-dependent way?

### PR DESCRIPTION
**Pull request by mstimberg**
As discussed in #53, this removes our fancy "pre-compile GeNN libraries and ship them with BrianGeNN" approach. Users should install GeNN manually and then install Brian2GeNN from source via pip.

Closes #53

### CODE REVIEW

**Comment by mstimberg** [comment]
@tnowotny , @thesamovar this is fine with you, right? After merging, I think it would be time to do the 1.2 release (given that we only release the source package, doing the release will be straight-forward...).

I think I'll also move our existing conda packages to an `archive` label or something like that. This will prevent users from installing an outdated version by following older installation instructions.

**Comment by mstimberg** [comment]
PS: Don't worry about the build failure, we test everything twice (once on the branch and once after merging -- given that nothing else changed on the master branch, the two are perfectly identical) and one of the two ran fine, the other took to long for the appveyor timeout.

**Comment by tnowotny** [comment]
Yes, as discussed, I think this is the most sensible option. I would hope it leads to a lot less trouble with compiler and library versions etc
so, ok to go forward from my perspective.

**Comment by thesamovar** [comment]
Yeah, it's a shame to not have it be one line install, but that's kind of unrealistic anyway and we don't want to have a heavy maintenance burden on this.

**Pull request merged**
