### PR TITLE
Include custom headers in `model.cpp`

### PR DESCRIPTION
**Pull request by denisalevi**
Fix for issue #131. I only included headers defined via `prefs.codegen.cpp.headers`.

### CODE REVIEW

**Comment by mstimberg** [comment]
Thanks for the PR! I'm happy with the change in general, but for consistency with the other templates maybe rather use:
```jinja2
{% for name in user_headers | sort %}
#include {{name}}
{% endfor %}
```
? I don't think we need to support two types of syntaxes to specify headers here.
Also, maybe use `user_headers = self.headers + prefs['codegen.cpp.headers']` as in the other places? I am not quite sure why we use `self.headers` elsewhere (it is an empty list anyway), but it might come in handy some day I guess.

**Comment by mstimberg** [comment]
Oops, sorry... I just saw that the code I mentioned is used in `brian2`, not in `brian2genn`...

**Review by mstimberg — APPROVED** [review]
In the long-term we should make Brian2 and Brian2GeNN consistent with respect to the header syntax, but that's independent of this PR. Happy to merge things.

**Comment by mstimberg** [comment]
Oh, but note that `brian2genn`  does not work (yet) with `brian2` master, due to the changes in the synapse generator.

**Comment by denisalevi** [comment]
Thanks for the quick merge and the hint! I will stick with the latest brian2 release for the benchmarks.

**Pull request merged**
